### ISSUE TITLE
The yellow color is overly mustardy

### ISSUE THREAD

**Issue by rchande** [Pilchie/xunit.runner.wpf#17]
Thoughts @dpoeschl @Pilchie ?

**Comment by dpoeschl** [comment]
As per [last week's Planet Money](http://www.npr.org/sections/money/2015/08/07/429720443/17-205-people-guessed-the-weight-of-a-cow-heres-how-they-did), we should have a large number of people guess the hex code for a good yellow "skipped" indicator and just take their average.

**Comment by jaredpar** [comment]
I think it looks a bit too purple for my taste

**Comment by DustinCampbell** [comment]
Is this a real issue?
