### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by shvr** [Pilchie/xunit.runner.wpf#90]
No license has been provided for the project. Can you clarify what license the source is under?

I need to work on a custom GUI for running xunit tests (internal to my company) and being able to reference this code would be quite helpful.

Cheers.

**Comment by Pilchie** [comment]
Thanks for the prompt.  I'm discussing it with a few contributors. My expectation is we'll land on either MIT or Apache 2.

**Comment by Pilchie** [comment]
Sorry for delay.  Submitted #91 to add an Apache 2 license.
